Vagrant.configure("2") do |config|

  config.vm.define "Vagrant-ubuntu"
  config.vm.box = "ubuntu/xenial64"


    config.vm.hostname = "test1"
    config.vm.network "private_network", ip: "11.11.11.11"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--acpi",   "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--cpus",   "1"]
  end

end

